name: container
on: [push,workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ubuntu:latest
    steps:
      - name: fetch code
        uses: actions/checkout@v4
      - name: Npm
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
        working-directory: angular-frontend
      - run: npm install -g @angular/cli  
      - run: npm run build
        working-directory: angular-frontend
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: angular-frontend/dist        
        
