name: Build and Run Docker Image
on: [push,workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t frontend .
        working-directory: angular-frontend

      - name: Run Docker Container
      - run: docker run -d -p 80:80 frontend
      - run: docker ps
      
