name: JOB2
on: [push, workflow_dispatch]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v4
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@< 3.8.8 >
      - run: mvn -V ...
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
      - name: Install dependencies
        run: mvn clean package
        working-directory: spring-backend
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-backend-artifact
          path: spring-backend/*.jar
  test:
    needs: builds
    runs-on: ubuntu-latest
    steps:
      - name: Get Code 
        uses: actions/checkout@v4
      - name: cache dependencies
     
      - name: Test
        run: mvn tets
        working-directory: spring-backend
      

    
