name: JOB2
on: [push,workflow_dispatch]
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps: 
      - name: fetch code
      - name: fetch code
      - uses: actions/checkout@v4
      - name: setup Nodejs
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
        working-directory: angular-frontend
      - run: npm install -g @angular/cli
      - run: ng build
      - name: upload Artifact
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: angular-frontend/dist/