name: JOB2
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: angular-frontend

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular project
        run: ng build --configuration=production
        working-directory: angular-frontend

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: angular-frontend/dist/
