name: env job
on: [push,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: fetch code
        uses: actions/checkout@v4
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: angular-frontend-${{ hashFiles('**/package-lock.json') }}
      - name: Output information
        run: |
          echo "${{ secrets.MYSQL_PASSWORD }}"
          echo "${{ env.MYSQL_ROOT_PASSWORD }}"
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: output info
        run: echo "${{ secrets.MYSQL_USER }}"
