name: env job
on: [push,workflow_dispatch]
env: 
  MYSQL_USER: admin
jobs:
  build:
    env:
      MYSQL_PASSWORD: asdert
      MYSQL_ROOT_PASSWORD: vbfgqwer23
    runs-on: ubuntu-latest
    steps:
      - name: fetch code
        uses: actions/checkout@v4
      - name: setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Cache
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: angular-frontend-${{ hashFiles('**/package-lock.json') }}
      - name: Output information
        run: echo "${{ env.MYSQL_PASSWORD }}"
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: output info
        run: echo "$ {{ env.MYSQL_USER }}"
