name: Deploy on S3
on: push
jobs:
  s3-push:
    runs-on: ubuntu-latest
    steps: 
      - name: fetsch Code
        uses: actions/checkout@v4
      - name: Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm install
        run: npm install
        working-directory: angular-frontend
      - run: npm install -g @angular/cli
      - run: npm run build
        working-directory: angular-frontend
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-frontend
          path: angular-frontend/dist/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Deploy static files to AWS S3
        id: aws-deploy-s3
        uses: oneyedev/aws-deploy-s3@v2
        with:
          region: ap-south-1
          bucket: giyu-123
          source: angular-frontend/dist/
          target: /
